/**
 * Prefix root-absolute public paths with Vite's base so the site works
 * when served from a subpath (e.g. GitHub Pages `/Portfolio/`).
 * Leaves relative paths, external URLs, and non-strings untouched.
 */
export function withBase(path) {
  if (typeof path !== 'string' || path === '') return path;
  if (!path.startsWith('/') || path.startsWith('//')) return path;
  const base = import.meta.env.BASE_URL || '/';
  return `${base.replace(/\/$/, '')}${path}`;
}

/**
 * Lite variant of a raster project image (`store.webp` -> `store-lite.webp`).
 * Generated by scripts/make-lite-images.mjs (640px, q55). Vectors pass through.
 */
export function liteSrc(src) {
  if (typeof src !== 'string' || src === '') return src;
  const m = src.match(/^(.*)\.(webp|png|jpe?g)$/i);
  if (!m) return src;
  return `${m[1]}-lite.webp`;
}
